// GENERATED by bench/law-cost.mjs --write (D-036). Do not edit by hand.
// Multiplex LAW COUNT ranking: the first N laws of LAW_PRIORITY are the ones a
// full-tier preview keeps at LAW COUNT = N (each sim still only runs laws it
// has on). Order: the 16-law light set (life, energy and reproduction first),
// then the remaining laws from cheapest to most expensive, measured by
// leave-one-out on a 1,000-particle all-laws bench:solver world (all-laws
// median 157.5 ms/tick; the comment is the ms/tick removing that law saved,
// noise ≈ ±2 ms, so the order among cheap laws is approximate but fixed).
import { LAW_INDEXES, LAW_COUNT } from '../constants.js';
import { lawMaskFor } from './previewLaws.js';

export const LAW_PRIORITY = Object.freeze([
  'LIFE', // 1: 12.43 ms/tick
  'ENERGY', // 2: 12.73 ms/tick
  'REPRO', // 3: 12.97 ms/tick
  'GRAV', // 4: 17.52 ms/tick
  'DRAG', // 5: 1.87 ms/tick
  'COLL', // 6: 16.42 ms/tick
  'ACCR', // 7: 10.78 ms/tick
  'ENTR', // 8: -12.64 ms/tick
  'HEAT', // 9: 2.60 ms/tick
  'BUOYANCY', // 10: 8.97 ms/tick
  'TIDE', // 11: -0.15 ms/tick
  'FIELD', // 12: 2.50 ms/tick
  'CONVECTION', // 13: 14.68 ms/tick
  'LATENT_HEAT', // 14: 8.03 ms/tick
  'EQUILIBRIUM', // 15: -3.76 ms/tick
  'GLOW', // 16: 9.41 ms/tick
  'MEMORY', // 17: -19.93 ms/tick
  'ISOMERIZATION', // 18: -18.54 ms/tick
  'CHIRALITY', // 19: -13.16 ms/tick
  'CATALYSIS_LAW', // 20: -12.15 ms/tick
  'EXOTHERMIC', // 21: -10.33 ms/tick
  'PLANCK', // 22: -10.14 ms/tick
  'SINGULARITY', // 23: -7.82 ms/tick
  'PERCEPTION', // 24: -7.42 ms/tick
  'COLD', // 25: -3.71 ms/tick
  'FRICTION', // 26: -3.30 ms/tick
  'COMMS', // 27: -3.17 ms/tick
  'POLARIZATION', // 28: -2.02 ms/tick
  'ENCRYPTION', // 29: -1.16 ms/tick
  'UNCERTAINTY', // 30: -0.83 ms/tick
  'PRECIPITATION', // 31: -0.81 ms/tick
  'MASS_INERTIA', // 32: -0.64 ms/tick
  'WILL', // 33: -0.61 ms/tick
  'SUBLIMATION', // 34: 0.06 ms/tick
  'BOSONIC', // 35: 0.20 ms/tick
  'STIGMERGY', // 36: 0.98 ms/tick
  'IONIZATION', // 37: 1.04 ms/tick
  'FATE', // 38: 1.64 ms/tick
  'CONSTRAINT', // 39: 1.68 ms/tick
  'RADIATION', // 40: 1.91 ms/tick
  'ELECTRIC_FIELD', // 41: 1.99 ms/tick
  'DIMENSIONALITY', // 42: 2.19 ms/tick
  'ALLOY', // 43: 2.25 ms/tick
  'OBSERVER', // 44: 2.72 ms/tick
  'TIME_DILATION', // 45: 4.21 ms/tick
  'EXPANSION', // 46: 4.22 ms/tick
  'CURRENT', // 47: 4.31 ms/tick
  'PLASMA', // 48: 4.58 ms/tick
  'TELEPORT', // 49: 4.58 ms/tick
  'SENESCENCE', // 50: 5.04 ms/tick
  'SHIELDING', // 51: 5.04 ms/tick
  'NAVIGATION', // 52: 5.59 ms/tick
  'SYMBOL', // 53: 5.61 ms/tick
  'SPIN', // 54: 5.87 ms/tick
  'PHASE_RADIATION', // 55: 6.64 ms/tick
  'ACIDITY', // 56: 6.99 ms/tick
  'VOID', // 57: 7.47 ms/tick
  'SUPERPOSITION', // 58: 7.61 ms/tick
  'METRIC', // 59: 7.79 ms/tick
  'LANGUAGE', // 60: 8.08 ms/tick
  'POLYMER', // 61: 8.14 ms/tick
  'PHENOTYPE', // 62: 9.03 ms/tick
  'CRYSTALLIZATION', // 63: 9.64 ms/tick
  'CLAIRVOYANCE', // 64: 9.65 ms/tick
  'TORQUE', // 65: 9.82 ms/tick
  'CONTACT', // 66: 9.92 ms/tick
  'WAVE_PARTICLE', // 67: 10.16 ms/tick
  'BOIL', // 68: 10.40 ms/tick
  'SOLVATION', // 69: 10.64 ms/tick
  'WAVEFUNCTION', // 70: 10.70 ms/tick
  'ADHESION', // 71: 10.76 ms/tick
  'ELECTROLYSIS', // 72: 11.02 ms/tick
  'PHOTOLYSIS', // 73: 11.18 ms/tick
  'PROTOCOL', // 74: 11.48 ms/tick
  'ENTANGLEMENT', // 75: 11.70 ms/tick
  'SYMBIOSIS', // 76: 11.86 ms/tick
  'SPECTRAL', // 77: 11.95 ms/tick
  'FEEDBACK', // 78: 12.22 ms/tick
  'HIBERNATION', // 79: 12.24 ms/tick
  'OXIDATION', // 80: 12.69 ms/tick
  'GENOTYPE', // 81: 12.89 ms/tick
  'CODE', // 82: 12.89 ms/tick
  'HYPERPLANE', // 83: 13.22 ms/tick
  'RUNAWAY', // 84: 13.48 ms/tick
  'MIND', // 85: 13.53 ms/tick
  'INDUCTANCE', // 86: 13.53 ms/tick
  'NEUTRALIZATION', // 87: 14.05 ms/tick
  'ANTIMATTER', // 88: 14.40 ms/tick
  'TELEPATHY', // 89: 14.72 ms/tick
  'MOMENTUM', // 90: 14.76 ms/tick
  'WRAP', // 91: 14.79 ms/tick
  'PREDATION', // 92: 15.12 ms/tick
  'RESISTANCE', // 93: 15.15 ms/tick
  'DECOHERENCE', // 94: 15.45 ms/tick
  'SYNCHRONICITY', // 95: 15.67 ms/tick
  'STOICHIOMETRY', // 96: 15.78 ms/tick
  'CHAOS', // 97: 16.16 ms/tick
  'HISTORY', // 98: 16.22 ms/tick
  'IMMUNITY', // 99: 16.24 ms/tick
  'CONSCIOUSNESS', // 100: 16.36 ms/tick
  'LEARN', // 101: 16.89 ms/tick
  'FERMIONIC', // 102: 16.97 ms/tick
  'FRAGMENTATION', // 103: 16.97 ms/tick
  'CHARGE_LAW', // 104: 17.17 ms/tick
  'TOPOLOGY', // 105: 17.34 ms/tick
  'ANTENNA', // 106: 17.87 ms/tick
  'ORDER', // 107: 18.02 ms/tick
  'ADIABATIC', // 108: 18.04 ms/tick
  'PATTERN', // 109: 19.24 ms/tick
  'PLANETARY', // 110: 19.40 ms/tick
  'REDUCTION', // 111: 19.47 ms/tick
  'CULTURE', // 112: 19.50 ms/tick
  'TRACK', // 113: 19.57 ms/tick
  'PARASITE', // 114: 19.62 ms/tick
  'ASTRAL', // 115: 19.63 ms/tick
  'DISCHARGE', // 116: 19.64 ms/tick
  'COHERENCE', // 117: 19.66 ms/tick
  'HORIZON', // 118: 19.67 ms/tick
  'PRECOGNITION', // 119: 19.69 ms/tick
  'RESONANCE', // 120: 19.91 ms/tick
  'TUNNELING', // 121: 20.11 ms/tick
  'CONDENSE', // 122: 20.50 ms/tick
  'DEPOSIT', // 123: 20.77 ms/tick
  'FLUX', // 124: 20.86 ms/tick
  'AFFINITY', // 125: 21.63 ms/tick
  'MAGNETISM', // 126: 22.02 ms/tick
  'SIGNAL_BOOST', // 127: 22.03 ms/tick
  'PREDICT', // 128: 22.52 ms/tick
  'RADIATION_PRESSURE', // 129: 22.53 ms/tick
  'MELT', // 130: 24.78 ms/tick
  'AUTOCATALYSIS', // 131: 25.53 ms/tick
  'SOUL_LAW', // 132: 26.22 ms/tick
  'SUPERCONDUCTIVITY', // 133: 33.95 ms/tick
  'COMPRESSION', // 134: 36.39 ms/tick
  'CAPACITANCE', // 135: 42.45 ms/tick
  'BOND', // 136: 92.76 ms/tick
]);
export const LIGHT_LAW_COUNT = 16;

/** Clamp a LAW COUNT value to 1…LAW_COUNT (non-numbers → LAW_COUNT, i.e. all laws). */
export function sanitizeLawCount(v) {
  const n = Math.round(Number(v));
  return Number.isFinite(n) ? Math.max(1, Math.min(LAW_COUNT, n)) : LAW_COUNT;
}

/** Law mask of the top-N laws of LAW_PRIORITY. */
export function lawCountMask(n) {
  return lawMaskFor(LAW_PRIORITY.slice(0, sanitizeLawCount(n)));
}

if (LAW_PRIORITY.length !== LAW_COUNT || new Set(LAW_PRIORITY).size !== LAW_COUNT || LAW_PRIORITY.some((l) => LAW_INDEXES[l] === undefined)) {
  throw new Error('lawRanking: LAW_PRIORITY must list every law exactly once');
}
