// GENERATED by bench/law-cost.mjs --write (D-036). Do not edit by hand.
// Multiplex LAW COUNT ranking: the first N laws of LAW_PRIORITY are the ones a
// full-tier preview keeps at LAW COUNT = N (each sim still only runs laws it
// has on). Order: the 16-law light set (life, energy and reproduction first),
// then the remaining laws from cheapest to most expensive, measured by
// leave-one-out on a 1,000-particle all-laws bench:solver world (all-laws
// median 141.3 ms/tick; the comment is the ms/tick removing that law saved,
// noise ≈ ±2 ms, so the order among cheap laws is approximate but fixed).
import { LAW_INDEXES, LAW_COUNT } from '../constants.js';
import { lawMaskFor } from './previewLaws.js';

export const LAW_PRIORITY = Object.freeze([
  'LIFE', // 1: -1.16 ms/tick
  'ENERGY', // 2: -0.59 ms/tick
  'REPRO', // 3: 6.22 ms/tick
  'GRAV', // 4: -7.79 ms/tick
  'DRAG', // 5: -4.94 ms/tick
  'COLL', // 6: 6.68 ms/tick
  'ACCR', // 7: -0.94 ms/tick
  'ENTR', // 8: -19.05 ms/tick
  'HEAT', // 9: -1.89 ms/tick
  'BUOYANCY', // 10: -4.06 ms/tick
  'TIDE', // 11: -13.05 ms/tick
  'FIELD', // 12: -7.86 ms/tick
  'CONVECTION', // 13: -1.54 ms/tick
  'LATENT_HEAT', // 14: -6.87 ms/tick
  'EQUILIBRIUM', // 15: -5.14 ms/tick
  'GLOW', // 16: 5.54 ms/tick
  'FATE', // 17: -25.54 ms/tick
  'EXOTHERMIC', // 18: -22.29 ms/tick
  'CATALYSIS_LAW', // 19: -22.25 ms/tick
  'WILL', // 20: -20.86 ms/tick
  'WAVEFUNCTION', // 21: -20.65 ms/tick
  'HISTORY', // 22: -20.11 ms/tick
  'ACIDITY', // 23: -18.49 ms/tick
  'SUBLIMATION', // 24: -17.57 ms/tick
  'MEMORY', // 25: -16.65 ms/tick
  'SINGULARITY', // 26: -16.61 ms/tick
  'EXPANSION', // 27: -15.41 ms/tick
  'LANGUAGE', // 28: -14.91 ms/tick
  'ALLOY', // 29: -14.41 ms/tick
  'PRECIPITATION', // 30: -13.72 ms/tick
  'UNCERTAINTY', // 31: -13.44 ms/tick
  'VOID', // 32: -13.05 ms/tick
  'SHIELDING', // 33: -13.02 ms/tick
  'MASS_INERTIA', // 34: -12.99 ms/tick
  'ISOMERIZATION', // 35: -12.95 ms/tick
  'HYPERPLANE', // 36: -12.84 ms/tick
  'ADIABATIC', // 37: -12.75 ms/tick
  'COLD', // 38: -12.31 ms/tick
  'DIMENSIONALITY', // 39: -12.27 ms/tick
  'PLANCK', // 40: -12.25 ms/tick
  'SPIN', // 41: -11.95 ms/tick
  'COMMS', // 42: -11.68 ms/tick
  'IONIZATION', // 43: -11.38 ms/tick
  'ENCRYPTION', // 44: -11.34 ms/tick
  'TORQUE', // 45: -10.77 ms/tick
  'FRICTION', // 46: -10.75 ms/tick
  'RADIATION', // 47: -10.57 ms/tick
  'POLARIZATION', // 48: -10.00 ms/tick
  'OBSERVER', // 49: -9.35 ms/tick
  'CHIRALITY', // 50: -9.34 ms/tick
  'ANTIMATTER', // 51: -9.31 ms/tick
  'STIGMERGY', // 52: -9.13 ms/tick
  'SUPERPOSITION', // 53: -9.13 ms/tick
  'TIME_DILATION', // 54: -8.57 ms/tick
  'PATTERN', // 55: -8.39 ms/tick
  'CURRENT', // 56: -8.23 ms/tick
  'PLASMA', // 57: -8.14 ms/tick
  'SYMBOL', // 58: -7.95 ms/tick
  'METRIC', // 59: -7.93 ms/tick
  'MIND', // 60: -7.81 ms/tick
  'PHENOTYPE', // 61: -7.62 ms/tick
  'PERCEPTION', // 62: -7.36 ms/tick
  'CODE', // 63: -7.06 ms/tick
  'RESISTANCE', // 64: -6.54 ms/tick
  'AFFINITY', // 65: -5.85 ms/tick
  'CONSTRAINT', // 66: -5.82 ms/tick
  'BOIL', // 67: -5.64 ms/tick
  'TUNNELING', // 68: -5.45 ms/tick
  'SOLVATION', // 69: -4.81 ms/tick
  'ELECTRIC_FIELD', // 70: -4.68 ms/tick
  'TELEPORT', // 71: -4.62 ms/tick
  'PREDATION', // 72: -4.56 ms/tick
  'HORIZON', // 73: -4.46 ms/tick
  'FEEDBACK', // 74: -4.12 ms/tick
  'ANTENNA', // 75: -4.03 ms/tick
  'SOUL_LAW', // 76: -3.25 ms/tick
  'POLYMER', // 77: -3.01 ms/tick
  'RUNAWAY', // 78: -2.92 ms/tick
  'CHAOS', // 79: -2.91 ms/tick
  'PHOTOLYSIS', // 80: -2.74 ms/tick
  'SPECTRAL', // 81: -2.65 ms/tick
  'PHASE_RADIATION', // 82: -2.46 ms/tick
  'NAVIGATION', // 83: -2.22 ms/tick
  'RADIATION_PRESSURE', // 84: -1.99 ms/tick
  'SYMBIOSIS', // 85: -1.94 ms/tick
  'WRAP', // 86: -1.60 ms/tick
  'DEPOSIT', // 87: -1.25 ms/tick
  'COHERENCE', // 88: -1.15 ms/tick
  'ELECTROLYSIS', // 89: -0.66 ms/tick
  'OXIDATION', // 90: -0.65 ms/tick
  'WAVE_PARTICLE', // 91: -0.65 ms/tick
  'INDUCTANCE', // 92: -0.62 ms/tick
  'REDUCTION', // 93: -0.19 ms/tick
  'RESONANCE', // 94: 0.24 ms/tick
  'IMMUNITY', // 95: 0.35 ms/tick
  'PLANETARY', // 96: 0.37 ms/tick
  'BOSONIC', // 97: 0.44 ms/tick
  'ORDER', // 98: 0.75 ms/tick
  'PARASITE', // 99: 0.88 ms/tick
  'CLAIRVOYANCE', // 100: 0.98 ms/tick
  'ASTRAL', // 101: 1.09 ms/tick
  'SYNCHRONICITY', // 102: 1.13 ms/tick
  'FRAGMENTATION', // 103: 1.17 ms/tick
  'CONDENSE', // 104: 1.23 ms/tick
  'STOICHIOMETRY', // 105: 1.48 ms/tick
  'ENTANGLEMENT', // 106: 1.54 ms/tick
  'GENOTYPE', // 107: 2.38 ms/tick
  'ADHESION', // 108: 2.59 ms/tick
  'DECOHERENCE', // 109: 2.67 ms/tick
  'TOPOLOGY', // 110: 2.79 ms/tick
  'PREDICT', // 111: 2.87 ms/tick
  'TELEPATHY', // 112: 2.95 ms/tick
  'PROTOCOL', // 113: 2.98 ms/tick
  'HIBERNATION', // 114: 3.18 ms/tick
  'SIGNAL_BOOST', // 115: 3.49 ms/tick
  'MOMENTUM', // 116: 3.77 ms/tick
  'NEUTRALIZATION', // 117: 3.88 ms/tick
  'FLUX', // 118: 4.07 ms/tick
  'FERMIONIC', // 119: 4.21 ms/tick
  'CULTURE', // 120: 4.40 ms/tick
  'PRECOGNITION', // 121: 4.52 ms/tick
  'CHARGE_LAW', // 122: 4.63 ms/tick
  'DISCHARGE', // 123: 5.09 ms/tick
  'SENESCENCE', // 124: 5.92 ms/tick
  'CONSCIOUSNESS', // 125: 5.98 ms/tick
  'CONTACT', // 126: 6.03 ms/tick
  'TRACK', // 127: 6.07 ms/tick
  'AUTOCATALYSIS', // 128: 7.12 ms/tick
  'MELT', // 129: 7.13 ms/tick
  'MAGNETISM', // 130: 7.38 ms/tick
  'LEARN', // 131: 7.39 ms/tick
  'CRYSTALLIZATION', // 132: 9.22 ms/tick
  'COMPRESSION', // 133: 10.00 ms/tick
  'SUPERCONDUCTIVITY', // 134: 11.67 ms/tick
  'CAPACITANCE', // 135: 28.98 ms/tick
  'BOND', // 136: 58.67 ms/tick
]);
export const LIGHT_LAW_COUNT = 16;

/** Clamp a LAW COUNT value to 1…LAW_COUNT (non-numbers → LAW_COUNT, i.e. all laws). */
export function sanitizeLawCount(v) {
  const n = Math.round(Number(v));
  return Number.isFinite(n) ? Math.max(1, Math.min(LAW_COUNT, n)) : LAW_COUNT;
}

/** Law mask of the top-N laws of LAW_PRIORITY. */
export function lawCountMask(n) {
  return lawMaskFor(LAW_PRIORITY.slice(0, sanitizeLawCount(n)));
}

if (LAW_PRIORITY.length !== LAW_COUNT || new Set(LAW_PRIORITY).size !== LAW_COUNT || LAW_PRIORITY.some((l) => LAW_INDEXES[l] === undefined)) {
  throw new Error('lawRanking: LAW_PRIORITY must list every law exactly once');
}
