export const DEFAULT_DNA_STRIDE = 64;
export const DNA_PACK_MAX = 65535;
export const DNA_COUNT = 64;

export const DNA_INDEXES = {
  FORCE: 0,
  VISCOSITY: 1,
  TORQUE: 2,
  JITTER: 3,
  POLARITY: 4,
  ALPHA: 5,
  SYMMETRY: 6,
  HIDDEN_MASS: 7,
  STIFFNESS: 8,
  FUSION: 9,
  BIRTH_RATE: 10,
  DEATH_RATE: 11,
  MUTATION: 12,
  SIGNAL_RESP: 13,
  PULSE_RATE: 14,
  TIDAL: 15,
  FUSION_MOMENTUM: 16,
  FUSION_TIME: 17,
  NEIGHBORHOOD_RADIUS: 18,
  SIGNAL_STRENGTH: 19,
  SIGNAL_DECAY: 20,
  PROPAGATION_SPEED: 21,
  TUNING_CH1: 22,
  TUNING_CH2: 23,
  TUNING_CH3: 24,
  TUNING_CH4: 25,
  INERTIA: 26,
  FRICTION: 27,
  MAX_VELOCITY: 28,
  BASE_RADIUS: 29,
  ELASTICITY: 30,
  BOND_ANGLE: 31,
  CONDUCTIVITY: 32,
  MAGNETIC_MOMENT: 33,
  ENERGY_EFFICIENCY: 34,
  SEX_CHANCE: 35,
  PREDATION_BIAS: 36,
  REACTION_THRESHOLD: 37,
  CATALYSIS: 38,
  HEAT_OUTPUT: 39,
  MEMORY_DECAY: 40,
  SPECIES_AFFINITY: 41,
  DOMINANCE: 42,
  CROSSOVER_RATE: 43,
  EPIGENETIC_DRIFT: 44,
  HETEROZYGOSITY: 45,
  GENE_FLOW: 46,
  REPRESSOR: 47,
  ALLELE_COUNT: 48,
  EPIGENETIC_RATE: 49,
  HGT_RATE: 50,
  REPAIR_EFFICIENCY: 51,
  DRIFT_RATE: 52,
  SELECTION_SENSITIVITY: 53,
  SPECIATION_THRESHOLD: 54,
  ADAPTATION_RATE: 55,
  TRANSPOSON_RATE: 56,
  GENE_SILENCING: 57,
  RECOMBINATION_BIAS: 58,
  MUTAGEN_SENSITIVITY: 59,
  TELOMERE_LENGTH: 60,
  PLOIDY_LEVEL: 61,
  CODON_BIAS: 62,
  REGULATORY_DEPTH: 63,
};

export const DNA_META = [
  'Force', 'Viscosity', 'Torque', 'Jitter', 'Polarity', 'Alpha', 'Symmetry',
  'Hidden Mass', 'Stiffness', 'Fusion', 'Birth Rate', 'Death Rate', 'Mutation',
  'Signal Response', 'Pulse Rate', 'Tidal', 'Fusion Momentum', 'Fusion Time',
  'Neighborhood Radius', 'Signal Strength', 'Signal Decay', 'Propagation Speed',
  'Tuning Ch1', 'Tuning Ch2', 'Tuning Ch3', 'Tuning Ch4', 'Inertia', 'Friction',
  'Max Velocity', 'Base Radius', 'Elasticity', 'Bond Angle', 'Conductivity',
  'Magnetic Moment', 'Energy Efficiency', 'Sex Chance', 'Predation Bias',
  'Reaction Threshold', 'Catalysis', 'Heat Output', 'Memory Decay',
  'Species Affinity', 'Dominance', 'Crossover Rate', 'Epigenetic Drift',
  'Heterozygosity', 'Gene Flow', 'Repressor', 'Allele Count', 'Epigenetic Rate',
  'HGT Rate', 'Repair Efficiency', 'Drift Rate', 'Selection Sensitivity',
  'Speciation Threshold', 'Adaptation Rate', 'Transposon Rate', 'Gene Silencing',
  'Recombination Bias', 'Mutagen Sensitivity', 'Telomere Length', 'Ploidy Level',
  'Codon Bias', 'Regulatory Depth',
];

export const DNA_RANGES = [
  { min: -100, max: 100, default: 1.0 },
  { min: 0.5, max: 1.0, default: 0.98 },
  { min: -1, max: 1, default: 0 },
  { min: 0, max: 5.0, default: 0.05 },
  { min: -1, max: 1, default: 0 },
  { min: 0, max: 1, default: 0.5 },
  { min: -1, max: 1, default: 0 },
  { min: -5, max: 5, default: 0 },
  { min: 0.1, max: 5, default: 1.0 },
  { min: 0, max: 1, default: 0.5 },
  { min: 0, max: 10, default: 0.5 },
  { min: 0, max: 10, default: 0.1 },
  { min: 0, max: 10, default: 0.5 },
  { min: 0, max: 2, default: 1.0 },
  { min: 0, max: 1, default: 0.2 },
  { min: -1, max: 1, default: 0 },
  { min: 0, max: 50, default: 1.0 },
  { min: 0, max: 100, default: 2 },
  { min: 20, max: 500, default: 120 },
  { min: 0, max: 1, default: 0.5 },
  { min: 0.1, max: 0.99, default: 0.95 },
  { min: 0.01, max: 1.0, default: 0.5 },
  { min: 0, max: 1, default: 1 },
  { min: 0, max: 1, default: 1 },
  { min: 0, max: 1, default: 1 },
  { min: 0, max: 1, default: 1 },
  { min: 0.1, max: 2, default: 1.0 },
  { min: 0, max: 0.1, default: 0.01 },
  { min: 1, max: 50, default: 20 },
  { min: 0.2, max: 4, default: 0.4 },
  { min: 0, max: 1, default: 0.5 },
  { min: 0, max: 360, default: 0 },
  { min: 0, max: 1, default: 0.1 },
  { min: -1, max: 1, default: 0.1 },
  { min: 0, max: 10, default: 0.8 },
  { min: 0, max: 10, default: 0.05 },
  { min: 0, max: 20, default: 0 },
  { min: 10, max: 1000, default: 500 },
  { min: 1, max: 10, default: 1.0 },
  { min: 0, max: 1, default: 0.1 },
  { min: 0.9, max: 1.0, default: 0.99 },
  { min: -1.0, max: 1.0, default: 0.0 },
  { min: 0.0, max: 1.0, default: 0.5 },
  { min: 0.0, max: 0.5, default: 0.1 },
  { min: 0.0, max: 0.1, default: 0.01 },
  { min: 0.0, max: 1.0, default: 0.5 },
  { min: 0.0, max: 1.0, default: 0.2 },
  { min: -1.0, max: 1.0, default: 0.0 },
  { min: 1, max: 8, default: 2 },
  { min: 0, max: 1, default: 0.1 },
  { min: 0, max: 1, default: 0.05 },
  { min: 0, max: 1, default: 0.5 },
  { min: 0, max: 1, default: 0.1 },
  { min: 0, max: 1, default: 0.5 },
  { min: 0, max: 1, default: 0.5 },
  { min: 0, max: 1, default: 0.2 },
  { min: 0, max: 1, default: 0.05 },
  { min: 0, max: 1, default: 0.1 },
  { min: -1, max: 1, default: 0 },
  { min: 0, max: 1, default: 0.5 },
  { min: 0, max: 1, default: 0.5 },
  { min: 1, max: 4, default: 2 },
  { min: 0, max: 1, default: 0.5 },
  { min: 1, max: 10, default: 3 },
];
